converse/educations/urls.py
from django.urls import path
from . import views
from .views import Like_comment

app_name = 'educations'
urlpatterns = [
    path('', views.post_list, name='education_post_list'),
     path('all_educational_posts_view', views.list_load_Educational_posts_view, name='all_educational_posts_view'),
     path('create_education_post/', views.Create_Post,name='create_post'),
     path('<int:year>/<int:month>/<int:day>/<slug:post>/',         
          views.post_detail,         
          name='post_detail'),
     path('likes/<int:pk>/', views.like_post, name="post-like"),

    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    path('<int:post_id>/share/',         
          views.post_share, name='post_share'),

    path('edit_post/<int:pk>', views.Update_Post, name='edit_post'),

    path('<int:post_id>/comment/',         
           views.post_comment, name='post_comment'),
    #path('all_educational_comment_view/<int:post_id>', views.list_load_Education_comments_view, name='all_educational_comment_view'),
    path('comment/reply/', views.reply_page, name="reply"),
    path('<int:pk>/edit-comment/', views.Update_Comment, name='edit-comment'),
    path('edit_post/all_Education_Comments(request)', views.Update_Post, name='edit_post'),
    path('delete/<int:pk>', views.delete_post, name='post-delete'),
    path('delete/<int:pk>', views.delete_comment, name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like',  Like_comment.as_view(), name='comment-like'),

   
]

converse/educations/templates/education_comment/comment.html

{% load  education_tags %}
{% load static %}



{% block content %}  
 <!DOCTYPE HTML>
  <head>
  {{ form.media }}
  <style>
   
 
	.name {
	   margin-top:-47px; margin-left:31px;}
	  
	  
	button {
	   margin-bottom:25px; margin-top:15px; font-size:30px;}
	   }
   </style>
  </head>
  <body>
    <div class="ps-2" id="{{comment.id}}" >
     		
   
		  <div  class="card w-98 bg-100 shadow hover:shadow-lg shadow-inner"   style="  border:2px solid black;  margin-bottom:5px ">
		  {% if  comment.education_parent%}
			<div  id="comment-edits" >
		   <div tabindex="0"  class="btn btn-ghost btn-circle avatar" style=" ">
			<img  class="w-10 rounded-full" src="{{comment.education_parent.name.profile.photo.url}}" style="margin:3px"/>
		   </div>
			<span><strong style="color:blue; position:relative; top:-30px; ">{{comment.education_parent.name}}</strong></span>
			<div style="position:relative; top:-30px; margin-left:50px; ">
            <p class="w-50"> {{comment.education_parent.body|markdown}}</p>
			<figure class="px-10 pt-10">
              <img src="{{ comment.education_parent.comment_image_one.url }}"  alt="" style="height:150px"/>
			  <img src="{{ comment.education_parent.comment_image_two.url }}"  alt="" style="height:150px"/>
            </figure>
			
		   </div>
		    {% endif %}
           </div>
		    
	   <div class="w-98  bg-neutral shadow-xl shadow hover:shadow-lg shadow-inner" style="  margin:5px;  border-radius:10px">
         <div tabindex="0"  class="btn btn-ghost btn-circle avatar" style=" margin-top:-5px; ">
           <div class="w-10 rounded-full">
            <img alt="converse" src="{{ comment.name.profile.photo.url }}" />
           </div>
		   </div>
		  
		  <div class="name" style="margin-left:50px; color:white" >
           <strong style="color:blue; ">{{comment.name}}</strong>
		    
            {% if  comment.education_parent.name %} replied to <strong style="color:purple">{{comment.education_parent.name}}</strong>  {% endif %}
            <small class="text-muted">   <i> about {{ comment.created | timesince }} ago</i></small>
			<div  style="color:white" id="comment-edits">
			 <p>{{comment.body|markdown}}</p>
			  <figure class="px-10 pt-10">
                <img src="{{ comment.comment_image_one.url }}"  alt="" style="height:150px"/>
			    <img src="{{ comment.comment_image_two.url }}"  alt="" style="height:150px"/>
             </figure>
			 
			</div>
		  
		  
		
			
			
			   {%  if comment.edited %}
			  <i><p style="margin-left: 0px; color:grey;"> Edited  {{ comment.edited_date|timesince }} ago</p></i>
			 {% endif %}
		
		 
	    </div>  
			 
		<div style="margin-left:50px">
			{% if user.is_authenticated %}
             {% if request.user not in comment.likes.all %}
              <button hx-post="{% url 'educations:comment-like' post.pk comment.pk%}"  hx-swap="outerHTML" hx-target="this" class="remove-default-btn" ><b><i class="fa fa-thumbs-up" style="font-size:12px; color:white"></i> <span style="font-size:12px; color:white">{{ comment.likes.all.count }}</span></b></button>
			{% else %}
			  <button hx-post="{% url 'educations:comment-like' post.pk comment.pk%}"  hx-swap="outerHTML" hx-target="this" class="remove-default-btn" ><b><i class="fa fa-thumbs-up" style="font-size:12px; color:blue"></i> <span style="font-size:12px; color:blue">{{ comment.likes.all.count }}</span></b></button>
			{% endif %}	
              	
            <span><button class="btn  btn-sm"  onclick="handleReply({{comment.id}})">Reply</button></span>
			{% if request.user == comment.name %}
		 
			<span><button class="btn  btn-sm" hx-get="{% url 'educations:edit-comment'  comment.pk %}"  hx-swap="outerHTML" hx-target="this" >Edit</button></span>
		 
		   {% else %}
		   <span></span>
		   {% endif %}
			
             {% endif %}
		    
			 <div id="reply-form-container-{{comment.id}}" style="display:none">
            
                <form method="post" action="{% url 'educations:reply' %}" class="mt-3">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <input type="hidden" name="parent" value="{{comment.id}}">
                    <input type="hidden" name="post_url" value="{{post.get_absolute_url}}">


                    {{ form.as_p }}  

                    <div>
                        <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm" >Cancel</button>
                        <button type="submit" class="btn btn-primary btn-sm" >Submit</button>
                    </div>
                </form>
            </div>
		</div>
		</div>
        </div>
		
		 </div> 
	  
	
           
			 
			 
        </div>
	   </div>
	   </div>
       	
{% endblock %}
</body>

converse/educations/templates/education_comment/comment_confirm.html

{% load static %}
{% block content %}

<!DOCTYPE HTML>
<html>
<head>
   {{ form.media }} 
  <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous">
   </script>
 
</head>


<body>
 
 
 {% if comment %}
 <div id="comment_confirm_form">
  <p style="color:green">Congratulations, your comment has been added! Thanks</p>
  <button class="btn btn-active " hx-get="{% url 'educations:post_comment' post.id %}"
          hx-target="this"
		  hx-swap="outerHTML">
		  Comment Again
   </button>
    {% with post.education_comments.count as total_comments %}
		 
            <h3 class="mt-5">
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h3>
			
        {% endwith %}
	
		
      
         {% if not post.education_comments.all %}
            No comments yet
        
        {% else %}
		      
            {% for comment in post.get_comments %}
          
								
			  <p>  {% include 'education_comment/comment.html' with comment=comment %}</p>
			</div>  
			
            {% endfor %}
		
        {% endif %}
    </div>   
  <div >
   {% else %} 
   
    <form  id="forms" hx-post="{% url 'educations:post_comment' post.id %}" enctype="multipart/form-data" hx-target="#NewComment" hx-swap="innerHTML" hx-trigger="submit" hx-on::after-request="this.reset()">
	      {% csrf_token %}
		  
		  {{ widget.attrs.class }}
		<h1>Add comment</h1> 
        {{ form.as_p }}         
     <button class="btn btn-active btn-primary" type="submit"  id="editing">Send comment</button>
      <span ><a class="btn  btn-sm" href="javascript:history.go(-1)" hx-boost="true">cancel</a></span>
    </form>
 </div>	
  {% endif %} 
 
 
  
 {% endblock %}
 
 </body>
 </html>

converse/educations/templates/education_comment/comment_edit_form.html
{% load  education_tags %}
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
   {{ form.media }} 
  <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous">
   </script>
 
</head>


<body>
 
 
 {% if comment.edited %}
 <div id="edited-comment">
  <p style="margin-left:31px">{{comment.body.html|markdown}}</p>
   <i><p style="margin-left: 0px; color:red;"> This Comment has been Edited  {{ comment.edited_date|timesince }} ago</p></i>
  	{% if request.user == comment.name %}
  <button class="btn  btn-sm" hx-get="{% url 'educations:edit-comment' comment.pk %}" hx-target="#edited-comment" hx-swap="outerHTML">Edit</button>
	{% else %}
	<span></span>
	{% endif %}
 </div>

   {% else %} 
 
<div style="margin-bottom:100px">
<form method="post" action="{% url 'educations:edit-comment' comment.pk %}" enctype="multipart/form-data" hx-boost="true" id="edit-form">  

    {{ form.as_p }}  
    {% csrf_token %}  
    <input type="submit" value="Add comment" class="btn btn primary" style="margin:5px"  >
	<input type="hidden" name="next" value="{{ request.GET.next }}" />
	<span ><a class="btn  btn-sm" href="javascript:history.go(-0)" hx-boost="true">cancel</a></span>
</form>

</div>
{% endif %}

converse/educations/templates/education_comment/delete.html
{% block content %}  
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

 <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-
               L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous"></script>
  
 
	 
   <div hx-target="this" hx-swap="outerHTML">
    <form  >
    {% csrf_token %}
    <button  class="btn btn-danger" id="editing"
	  hx-delete="{% url 'educations:post-delete' comment.pk %}"
      hx-confirm="Are you sure, You want to delete this comment?"
      type="submit" >
      Delete
     </button>
   </form>
   
 </div>

{% endblock %}

converse/educations/templates/education_comment/pagination.html
<div id="pagination" class="join grid grid-cols-2" style="text-align:center; margin-left:-50px">  
  <span class="step-links" style="margin-left:40px">    
    {% if page.has_previous %}      
      <button class="join-item btn btn-outline" 
	  hx-get="?page={{ page.previous_page_number }}"
	  hx-target="body"
	  hx-swap="outerHTML">Previous
	  </button>    
    {% endif %}

  <span class="current" style="color:green; padding:5px">      
    Page {{ page.number }} of {{ page.paginator.num_pages }}    
  </span>    
  {% if page.has_next %}      
    <button class="join-item btn btn-primary"
	hx-get="?page={{ page.next_page_number }}"
    hx-target="body"
    hx-swap="outerHTML"	> more comments
	</button>    
  {% endif %}  
  </span> 
</div>

converse/educations/templates/education_comment/share.html

{% block title %}Share a post{% endblock %}

{% block content %} 
<head> 
  <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-
               L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous"></script>
	<style>
	input {
	  margin-bottom:7px;}
	</style>
</head>
 
    {% if sent %}    
        <h1>E-mail successfully sent</h1>    
        <p>      
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.    
        </p>
         <button class="btn btn-success"><a style="text-decoration:none;" href="{{ post.get_absolute_url }}">OK</a></button>		
    {% else %}    
        <h1>Share "{{ post.title }}" by e-mail</h1>  
      	<div hx-target="this" hx-swap="outerHTML">	
        <form style="margin:20px" hx-post="{% url "educations:post_share" post.id %}">
                
            {% csrf_token %}
            {{ widget.attrs.class }}
            {{ form.as_p }}  			
            <button class="btn btn-active btn-primary" type="submit"  id="editing">Send e-mail</button> 
             <span ><a class="btn  btn-sm" href="javascript:history.go(-0)" hx-boost="true">cancel</a></span> 			
        </form> 
      </div>		
    {% endif %} 
{% endblock %}
