converse/internationals/urls.py
from django.urls import path
from . import views
from .views import Like_comment

app_name = 'internationals'
urlpatterns = [
     path('', views.post_list, name='international_post_list'),
     path('all_international_posts_view', views.list_load_International_posts_view, name='all_international_posts_view'),
     path('edit_post/<int:pk>', views.Update_Post, name='edit_post'),
     path('delete/<int:pk>', views.delete_post, name='post-delete'),
     path('create_international_news_post/', views.Create_Post,name='create_post'),
     path('likes/<int:pk>/', views.like_post, name="post-like"),
     path('<int:year>/<int:month>/<int:day>/<slug:post>/',         
          views.post_detail,         
          name='post_detail'),

    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    path('<int:post_id>/share/',         
          views.post_share, name='post_share'),

    path('<int:post_id>/comment/',         
           views.post_comment, name='post_comment'),
    path('comment/reply/', views.reply_page, name="reply"),
    path('<int:pk>/edit-comment/', views.Update_Comment, name='edit-comment'),
    path('delete/<int:pk>', views.delete_comment, name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like',  Like_comment.as_view(), name='comment-like'),

   
]

converse/internationals/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
from PIL import Image
from taggit.managers import TaggableManager
from prose.fields import RichTextField
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.postgres.search import SearchVectorField, SearchVector
from django.contrib.postgres.indexes import GinIndex
# Create your models here.

class PublishedManager(models.Manager):    
    def get_queryset(self):        
        return super().get_queryset().filter(status=Internationals.Status.PUBLISHED) #status field must be set to PUBLISHED too
    
class DraftManager(models.Manager):    
    def get_queryset(self):        
        return super().get_queryset().filter(status=Internationals.Status.DRAFT)
    

class Internationals(models.Model): 
    User = get_user_model()
    
    class Status(models.TextChoices):    #the status we have choices we can select from among Draft, Published, Pending. That is what TextChoices does like Drop down list box in html 
        DRAFT = 'DF', 'Draft'    
        PUBLISHED = 'PB', 'Published'
        PENDING= 'PD', 'Pending'

    tags = TaggableManager()
    
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    #author field is saying that only registered and acceptable users can authored or write post and not anonymous person and the  a author can write as many post as possible and also delete his or her post 
    #Which author write(s) so so post(s)
    #If an author is deleted by admin maybe because of infractions, all the posts made by such User(author) will also be deleted(CASCADE)
    #unique_for_date will ensure no duplicate post with same slug in a particular day
    author = models.ForeignKey(User,                             
                                 on_delete=models.CASCADE,                   
                                related_name='international_posts' )
    body = RichTextField()
    publish = models.DateTimeField(default=timezone.now)  
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    edited = models.BooleanField(default=False)
    #status field define our status choices by making the three  choices(draft, published, pending) available then making published as default by utilizing our Status child class
    status = models.CharField(max_length=2,                     
                                choices=Status.choices,                     
                                default=Status.DRAFT)
   
    news_image = models.ImageField(default=' ',
                             upload_to='photo-news')
    news_image_two = models.ImageField(default=' ', blank=True, upload_to='photo-news')
    news_image_three = models.ImageField(default=' ', blank=True, upload_to='photo-news')
    news_image_four = models.ImageField(default=' ',  blank=True, upload_to='photo-news')
    
    caption = models.CharField(max_length=250, blank=True ) 
    caption_two = models.TextField(max_length=10000, blank=True ) 
    caption_three = models.TextField(max_length=10000, blank=True) 
    caption_four = models.TextField(max_length=10000, blank=True ) 
    likes = models.ManyToManyField(User, related_name='liked_international_post', blank=True)
    total_likes = models.PositiveIntegerField(default=0)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', 
                                        related_query_name='hit_count_generic_relation')
    section_name = models.CharField(max_length=50, default='International News', editable=False)
    generatedField = models.GeneratedField(
        expression = SearchVector("title", config="english") + SearchVector("body", config="english"),
        output_field=SearchVectorField(),
        db_persist=True,
    )   
  

    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.  
    draft = DraftManager() 
    
 
 

    class Meta:  
        ordering = ['-publish'] #Last(newest) published to be at the top.
        indexes = [        
                models.Index(fields=['-publish']),
                models.Index(fields=['-total_likes']) ,
                GinIndex(fields=["generatedField"]),      
                      ]
        
   
     
    def __str__(self):       
         return self.title
    
    def get_absolute_url(self):
        return reverse('internationals:post_detail',
                       args=[self.publish.year,                             
                              self.publish.month,                             
                              self.publish.day,                             
                              self.slug])
    
    def get_comments(self):
        return self.international_comments.filter(international_parent=None).filter(active=True)
    



class Internationals_Comment(models.Model):
    User = get_user_model()     
    post = models.ForeignKey(Internationals,                            
                             on_delete=models.CASCADE,                             
                             related_name='international_comments') 
    
    name = models.ForeignKey(User,  on_delete=models.CASCADE,            
                                related_name='internationaluser_comments' )      
    email = models.EmailField()    
    body = RichTextField()
    comment_image_one  = models.ImageField(default=' ' , blank=True, upload_to='comment-photos')
    comment_image_two = models.ImageField(default=' ', blank=True, upload_to='comment-photos')
    created = models.DateTimeField(auto_now_add=True)    
    updated = models.DateTimeField(auto_now=True)    
    active = models.BooleanField(default=True)
    international_parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name="inter_replies", null=True)
    edited = models.BooleanField(default=False)
    edited_date = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='liked_international_comment', blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_international_comment', blank=True)
    section_name = models.CharField(max_length=50, default='International News Comment', editable=False)
    class Meta:        
        ordering = ['created']        
        indexes = [            
            models.Index(fields=['created']),       
              ]
    def __str__(self):        
        return f'Comment by {self.name} on {self.post}'
    
    def get_comments(self):
        return Internationals_Comment.objects.filter(international_parent=self).filter(active=True)

converse/internationals/forms.py
from django import forms
from .models import Internationals_Comment, Internationals 


class CommentForm(forms.ModelForm):
   class Meta:
    model = Internationals_Comment 
    fields =['body', 'comment_image_one', 'comment_image_two']
    
    
class PostForm(forms.ModelForm):
   news_image = forms.ImageField(required=True)
   class Meta:
    model = Internationals
    fields = fields =  [ 'title' , 'tags','news_image', 'caption', 'body', 'news_image_two', 'caption_two', 'news_image_three', 'caption_three', 'news_image_four', 'caption_four']
    widgets = {
          'caption' : forms.widgets.TextInput(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white', 'placeholder':'Brief Decription of Photo Above',}),
          'caption_two':forms.widgets.Textarea(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white mb-10', 'placeholder':'Use for Detailed Description of image_two if their is any',
                                                             'cols': 300, 'rows': 2}),
          'caption_three':forms.widgets.Textarea(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white mb-10', 'placeholder':'Use for Detailed Description of image_three if their is any',
                                                             'cols': 300, 'rows': 2}),
           'caption_four':forms.widgets.Textarea(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white mb-10', 'placeholder':'Use for Detailed Description of image_four if their is any',
                                                             'cols': 300, 'rows': 2}),
                  }  

class EmailPostForm(forms.Form): 
    
    name = forms.CharField(required=False, 
                               widget=forms.TextInput(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white', 'placeholder':'Input your name',
                                                                 'rows':2}))  
      
    to = forms.EmailField()    
    comments = forms.CharField(required=False, 
                               widget=forms.Textarea(attrs={'class': 'bg-gray-50 border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-grey-400 dark-white', 'placeholder':'Drop comment',
                                                                'cols': 15, 'rows':4}))

converse/internationals/templates/international_post/addInForum.html
{% extends "mybase2.html" %}
{% load static %}
{% block content %}

 <!DOCTYPE HTML>
 <html>
  <head>
   {{form.media}}
   


<script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-
               L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous"></script>
 <style>
 .edited-area p{ font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:green;}
 .edited-area a{text-decoration:underline; color:grey}
 .edited-area a:hover{color:blue}
 
  #id_title,
    #id_tags,
   #id_news_image,
    #id_news_image_two,
	#id_news_image_three,
	#id_news_image_four,
    #id_caption,
	#id_caption_two,
	#id_caption_three,
	#id_caption_four,
    #id_body {
      margin-bottom: 15px;
      width: 100%;
    }

    .helptext {
      color: green;
    }

    #id_body {
      border: 1px solid red
    }
 </style>
</head>
<body>
{% if post.edited %}
<div class="edited-area" style="margin:20%">
<p>Congratulations. You have successfully edited your post.</p><br><br>

<a  href="{{ post.get_absolute_url }}" hx-boost="true">Go back to the  post </a>
</div> 
{% else %}
<br>
<ul style="list-style-type:square">
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Use this Form to Edit your Post. A Text Editor is expected to display for Editing. If not, refresh the page to get the Text Editor Displayed</li>
  <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">There are four image upload buttons and their caption. The first is required while others are optional. Use them to add more image to the body of your post instead of the image upload icon in the text editor</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">You can use the caption to give detailed description of your image especially the other three images</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Do not Post hate speech on converseForums</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Do not Defame any character</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Remember that you are solely responsible for any post published by you</li>
</ul>
<br><br>
 <form  method ="post" action="{% url 'internationals:edit_post' post.pk %}" hx-boost="true" enctype='multipart/form-data' class= 'post-form' >
{% csrf_token %}
{{form.as_p}}

<input type="submit" value="Submit" class="btn btn primary" style="margin:5px"  >
<span ><a class="btn  btn-sm" href="javascript:history.go(-1)" hx-boost="true">cancel</a></span>
</form>
{% endif %}

{% endblock %}
</body>
</html>

converse/internationals/templates/international_post/create_post.html
{% extends "mybase2.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!DOCTYPE HTML>
<html>

<head>
  <meta charset="utf-8">
  <style>
    #id_title,
    #id_tags,
    #id_news_image,
    #id_news_image_two,
	#id_news_image_three,
	#id_news_image_four,
    #id_caption,
	#id_caption_two,
	#id_caption_three,
	#id_caption_four,
    #id_body {
      margin-bottom: 5px;
      width: 100%;
    }

    .helptext {
      color: green;
    }
  </style>
</head>

<body>
  <div class="newPost">
    <h1>Post on International News Section</h1>
<ul style="list-style-type:square">
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Use this Form To create your Post. A Text Editor is expected to display for Editing. If not, refresh the page to get the Text Editor Displayed</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">There are four image upload buttons and their caption. The first is required while others are optional. Use them to add more image to the body of your post instead of the image upload icon in the text editor</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">You can use the caption to give detailed description of your image especially the other three images</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Do not Post hate speech on converseForums</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Do not Defame any character</li>
 <li style="margin:5px;font-family:  Tahoma, Geneva, Verdana, sans-serif; font-size:16px; font-weight:200px; line-height: 1.5; color:blue;">Remember that you are solely responsible for any post published by you</li>
</ul>
<br><br>
    <form method='POST' enctype="multipart/form-data" class='post-form' style="margin:10px;">
      {% csrf_token %}
      {{form.media}}
      {{form.as_p}}
      <input type='Submit' class="btn btn-primary" value="submit">
    </form>
  </div>


  {% endblock %}
</body>

</html>

converse/internationals/templates/international_post/delete.html
{% block content %}  
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
</script>

 <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-
               L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous"></script>
  
 
	 
   <div hx-target="this" hx-swap="outerHTML">
    <form  >
    {% csrf_token %}
    <button  class="btn btn-danger" id="editing"
	  hx-delete="{% url 'internationals:post-delete' post.pk %}"
      hx-confirm="Are you sure, You want to delete this post?"
      type="submit" >
      Delete
     </button>
   </form>
   
 </div>

{% endblock %}

converse/internationals/templates/international_post/inter_home.html
{% extends "mybase2.html" %}
{% load static %}
{% load inter_tags %}
{% load crispy_forms_tags %}
 
   
      
{% block content %}	  



  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface|Poppins">
<script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-
               L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous">
	</script>
 

       
 <body style="background-color:silver;">

	{% include "international_post/partials/international_post_list.html"  %}
	   
	</body>   
		   
 {% endblock %}
 

converse/internationals/templates/international_post/international_details.html
 {% extends "mybase2.html" %}
 {% load inter_tags %}
 {% load static %}
 {% load hitcount_tags %}
 {% load social_share %}


{% block content %}
  <!DOCTYPE HTML>
  <head>
  {{ form.media }}
   <script src="https://unpkg.com/htmx.org@1.9.2"
               integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h"
               crossorigin="anonymous">
	</script>
	
       
</head>
<body style="body:100%; margin-left:2px;" id="body">
<a class="btn  btn-sm" href="javascript:history.go(-1)" hx-boost="true" > <span class="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-600"><i class="fa fa-arrow-left" aria-hidden="true"></i> </span></a>

 <div class="card w-96 bg-100 shadow-xl" style="width:100%">
    <div class="card-body" id="post-body">
      <h2 class="card-title">{{ post.title }}</h2>
      {% if request.user == post.author %}
      <p class="date">Published {{ post.publish }} by <a href="{% url 'my_activities' %}" class="name" style=" margin-left:-2px; text-decoration:underline; color:blue">{{ post.author }}</a></p>
      {% else %}
      <p class="date">Published {{ post.publish }} by <a href="{% url 'post_author' pk=post.author.pk %}" class="name" style="color:blue; margin-left:-2px"><i>{{ post.author }}</a></p>
      {% endif %}
       <hr>
	   <br>
       <figure class="px-10 pt-10">
        <img src="{{ post.news_image.url }}"  alt="" />
      </figure>
	  <figcaption>{{post.caption}}</figcaption>
	   <br>
       <p>{{ post.body|markdown }}</p><br>
	  <figure class="px-10 pt-10">
        <img src="{{ post.news_image_two.url }}"  alt="" />
      </figure>
	  <figcaption>{{post.caption_two}}</figcaption>
	  <figure class="px-10 pt-10">
        <img src="{{ post.news_image_three.url }}"  alt="" />
      </figure>
	  <figcaption>{{post.caption_three}}</figcaption>
	  <figure class="px-10 pt-10">
        <img src="{{ post.news_image_four.url }}"  alt=""/>
      </figure>
	  <figcaption>{{post.caption_four}}</figcaption>
       {% if post.edited %}
            
       <p style="margin-left: 0px; color:grey;">  Edited {{ post.updated|timesince }} ago</p>
            {% endif %}
	   {% if request.user == post.author %}
       {% with post.international_comments.count as total_comments %}
       {% if total_comments > 0 %}
    <div id="post-edit">
      <p style="color:brown">Post not Editable because a user has commented on it</p>
     {% else %}
    <a class="btn btn-primary" href="{% url 'internationals:edit_post' post.pk %}" >Edit Post </a>
    {% endif %}
    {% endwith %}
    {% else %}
    <span></span>
    {% endif %}
    </div>
   </div>
</div> 


{% if user.is_authenticated %}
<div id="main">
<div class="mt-4 flex gap-2">
<span class="inline-flex items-center gap-1   px-2 py-1 text-xs font-semibold text-blue-600">
<details class="dropdown">
  <summary class="btn m-1">Share</summary>
   <ul class="menu dropdown-content bg-base-100 rounded-box z-[1] w-15 p-2 shadow">
    <li><button hx-get="{% url 'internationals:post_share' post.id %}" hx-target="#main" hx-swap="outerHTML" ><i class='fa fa-envelope' aria-hidden='true' style='color:red'></i></button> </li>
	<li>{% post_to_facebook object_or_url "<i class='fa fa-facebook' aria-hidden='true' style='color:blue';'></i>" %}</li>
    <li>{% post_to_whatsapp object_or_url "<i class='fa fa-whatsapp' aria-hidden='true' style='color:green; ';'></i>" %}</li>
  </ul>
 </details>
</span>
<span class="inline-flex items-center gap-1   px-2 py-1 text-xs font-semibold text-blue-600">{% include "international_post/partials/like.html" %}</span>
<span class="inline-flex items-center gap-1 rounded-full bg-orange-50 px-2 py-1 text-xs font-semibold text-orange-600"><i class="fa fa-eye" aria-hidden="true"></i> {% get_hit_count for post %} </span>
</div>

{% else %}
<div class="mt-4 flex gap-2"  >
 <span class="inline-flex items-center gap-1   px-2 py-1 text-xs font-semibold text-blue-600"><button class="btn btn-active btn-primary" ><a href="{% url "login" %}?next={{request.path}}"  hx-boost="true">Login to share </a></button></span>
 <span class="inline-flex items-center gap-1   px-2 py-1 text-xs font-semibold text-blue-600" ><i class="fa fa-thumbs-up" style="font-size:12px; color:blue"></i> <span style="font-size:12px; color:blue">{{ post.likes.all.count }}</span></span>
 <span class="inline-flex items-center gap-1 rounded-full bg-orange-50 px-2 py-1 text-xs font-semibold text-orange-600"><i class="fa fa-eye" aria-hidden="true"></i> {% get_hit_count for post %} </span>
</div>
 {% endif %}
</div>
</div>
<hr>

<div class="card w-96 bg-100 shadow-xl" style="width:100%">
  <div class="card-body">
  <h2 class="card-title">Similar posts</h2>
   
  {% for post in similar_posts %}
  <ul class="specialLink">
    <li class="specialLink">  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  </ul>
   {% empty %}
      There are no similar posts yet.
   {% endfor %}
</div>
</div>
{% include 'international_post/partials/ranking.html' %}
<br>
  
<hr>
    
         
    <div  id="NewComment" >
        <div id="commentingForm">
       {% if user.is_authenticated %}
	     <button class="btn btn-active btn-primary" hx-get="{% url 'internationals:post_comment' post.id %}"hx-target="this" hx-swap="outerHTML" >Click to comment</button>
	   {% else %}
       <a class="btn btn-active btn-primary" href="{% url 'login' %}?next={{request.path}}">Login to comment on this post</a>
     {% endif %}
     </div>
	 <hr>
            {% with post.international_comments.count as total_comments %}
            <h3 class="mt-5">
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h3>
			
        {% endwith %}
	
		
      
        {% if not post.international_comments.all %}
           <p>Be the first to comment on this post</p>
        
        {% else %}
		      
            {% for comment in all_comments %}
          
			<div style=" margin-bottom:3px;">					
			  <p > {% include 'international_comment/comment.html' with comment=comment %}</p>
			</div>
			
            {% endfor %}
			
        {% endif %}
	 <!--{% include "pagination.html" with page=posts %}-->
      <p >{% include "international_comment/pagination.html" with page=all_comments %} </p>
	</div>

{% endblock %}


</body>





